### ISSUE TITLE
Failed Mutation - Why?

### ISSUE THREAD

**Issue by tloriato** [tloriato/stoccer-core#2]
Introduced in commit https://github.com/tloriato/stoccer-core/commit/a738237b2746b1eb478ea79135822027846636b9

_(rest of the code (others resolvers) is legacy but I don't think they should matter?)_

Given the following Mutation: 
```gql
mutation {
  signup(
    screenName: "Alice"
    email: "alice@prisma.io"
    password: "graphql"
  ) {
    token
    user {
      id
    }
  }
}
```

and the following resolver:

```javascript
async function signup(parent, args, context, info) {
  const password = await bcrypt.hash(args.password, 10)
  const balance = 0.0
  const stocks = []
  const subscribes = []
  const user = await context.prisma.createUser({...args, password, balance, stocks, subscribes})
  const token = jwt.sign({userId: user.id}, APP_SECRET)

  return {token, user}
}
```

We get the following error:

```
{
  "errors": [
    {
      "message": "Variable '$data' expected value of type 'UserCreateInput!' but got: {\"email\":\"alice@prisma.io\",\"password\":\"$2a$10$9EJGBNMrn3nXIM6NYeCqLeaAlHTg43fWXAubV8J94QStK.6ePELWa\",\"screenName\":\"Alice\",\"balance\":0,\"stocks\":[],\"subscribes\":[]}. Reason: 'stocks' Expected 'StockOwnershipCreateManyInput', found not an object. (line 1, column 11):\nmutation ($data: UserCreateInput!) {\n          ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "signup"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "result": {
            "data": null,
            "errors": [
              {
                "message": "Variable '$data' expected value of type 'UserCreateInput!' but got: {\"email\":\"alice@prisma.io\",\"password\":\"$2a$10$9EJGBNMrn3nXIM6NYeCqLeaAlHTg43fWXAubV8J94QStK.6ePELWa\",\"screenName\":\"Alice\",\"balance\":0,\"stocks\":[],\"subscribes\":[]}. Reason: 'stocks' Expected 'StockOwnershipCreateManyInput', found not an object. (line 1, column 11):\nmutation ($data: UserCreateInput!) {\n          ^",
                "locations": [
                  {
                    "line": 1,
                    "column": 11
                  }
                ]
              },
              {
                "message": "Variable '$data' expected value of type 'UserCreateInput!' but got: {\"email\":\"alice@prisma.io\",\"password\":\"$2a$10$9EJGBNMrn3nXIM6NYeCqLeaAlHTg43fWXAubV8J94QStK.6ePELWa\",\"screenName\":\"Alice\",\"balance\":0,\"stocks\":[],\"subscribes\":[]}. Reason: 'subscribes' Expected 'TeamCreateManyInput', found not an object. (line 1, column 11):\nmutation ($data: UserCreateInput!) {\n          ^",
                "locations": [
                  {
                    "line": 1,
                    "column": 11
                  }
                ]
              }
            ],
            "status": 200
          },
          "stacktrace": [
            "Error: Variable '$data' expected value of type 'UserCreateInput!' but got: {\"email\":\"alice@prisma.io\",\"password\":\"$2a$10$9EJGBNMrn3nXIM6NYeCqLeaAlHTg43fWXAubV8J94QStK.6ePELWa\",\"screenName\":\"Alice\",\"balance\":0,\"stocks\":[],\"subscribes\":[]}. Reason: 'stocks' Expected 'StockOwnershipCreateManyInput', found not an object. (line 1, column 11):",
            "mutation ($data: UserCreateInput!) {",
            "          ^",
            "    at BatchedGraphQLClient.<anonymous> (/Users/tloriato/Documents/Prog/graphQL-Tutorial/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)",
            "    at step (/Users/tloriato/Documents/Prog/graphQL-Tutorial/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)",
            "    at Object.next (/Users/tloriato/Documents/Prog/graphQL-Tutorial/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)",
            "    at fulfilled (/Users/tloriato/Documents/Prog/graphQL-Tutorial/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)",
            "    at <anonymous>",
            "    at process._tickCallback (internal/process/next_tick.js:118:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "signup": null
  }
}
```

-----

The problem is related to the obligatory fields (balance, stocks, subscribes), that are forcing me to pass an empty array. Without them it's working fine.

**Comment by tloriato** [comment]
Maybe if I add resolvers to both `stocks` and `subscribes` it would solve the problem.

I'll try it on Sunday night.

**Comment by tloriato** [comment]
Fixed on: https://github.com/tloriato/stoccer-core/commit/71746965c55aa055c525df3e12db43982ffec6f4
